# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/win-64/blas-1.0-mkl.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ca-certificates-2018.03.07-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/icc_rt-2017.0.4-h97af966_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/intel-openmp-2018.0.3-0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/msys2-conda-epoch-20160418-1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pandoc-2.2.1-h1a437c5_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-15.5.2-3.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/winpty-0.4.3-4.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gmp-6.1.0-2.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-libwinpthread-git-5.0.0.4634.697f757-2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl-2018.0.3-1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vc-14.1-h0510ff6_3.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/bzip2-1.0.6-hfa6e2cd_5.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/icu-58.2-ha66f8fd_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jpeg-9b-hb83a4c4_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libsodium-1.0.16-h9d3ae62_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libs-core-5.3.0-7.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/openssl-1.0.2o-h8ea7d77_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/python-3.6.6-hea74fb7_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/sqlite-3.24.0-h7602738_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/zlib-1.2.11-h8395fce_2.tar.bz2
https://repo.anaconda.com/pkgs/free/win-64/appdirs-1.4.3-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/asn1crypto-0.24.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/attrs-18.1.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/backcall-0.1.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/certifi-2018.4.16-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/colorama-0.3.9-py36h029ae33_0.tar.bz2
https://repo.anaconda.com/pkgs/free/win-64/constantly-15.1.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/decorator-4.3.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/entrypoints-0.2.3-py36_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/hdf4-4.2.13-h712560f_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/hdf5-1.10.2-hac2f561_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/idna-2.7-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/incremental-17.5.0-py36he5b1da3_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipython_genutils-0.2.0-py36h3c5d0ee_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/kiwisolver-1.0.1-py36h12c3424_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libpng-1.6.34-h79bbb47_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libssh2-1.8.0-hd619d38_4.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libgfortran-5.3.0-6.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/markupsafe-1.0-py36hfa6e2cd_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mistune-0.8.3-py36hfa6e2cd_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-1.14.5-py36h5c71026_4.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pandocfilters-1.4.2-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/parso-0.3.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pickleshare-0.7.4-py36h9de030f_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyasn1-0.4.4-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pycparser-2.18-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyparsing-2.2.0-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pytz-2018.5-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pywin32-223-py36hfa6e2cd_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/send2trash-1.5.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/simplegeneric-0.8.1-py36_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/sip-4.19.8-py36h6538335_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/six-1.11.0-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/testpath-0.3.1-py36h2698cfe_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/tornado-5.0.2-py36hfa6e2cd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/wcwidth-0.1.7-py36h3d5aa90_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/webencodings-0.5.1-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/wincertstore-0.2-py36h7fe50ca_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/zeromq-4.2.5-he025d50_1.tar.bz2
https://repo.anaconda.com/pkgs/free/win-64/zope-1.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/automat-0.7.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/cffi-1.11.5-py36h945400d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/cycler-0.10.0-py36h009560c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/freetype-2.8-h51f8f2c_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/html5lib-1.0.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/hyperlink-18.0.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jedi-0.12.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libcurl-7.61.0-h7602738_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libs-5.3.0-7.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyasn1-modules-0.2.2-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/python-dateutil-2.7.3-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyzmq-17.0.0-py36hfa6e2cd_3.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/qt-5.9.6-vc14h62aca36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/setuptools-39.2.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/traitlets-4.3.2-py36h096827d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/bleach-2.1.3-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/cryptography-2.2.2-py36hfa6e2cd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/curl-7.61.0-h7602738_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jinja2-2.10-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jsonschema-2.6.0-py36h7636477_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jupyter_core-4.4.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pygments-2.2.0-py36hb010967_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyqt-5.9.2-py36h1aa27d4_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pywinpty-0.5.4-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/wheel-0.31.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/zope.interface-4.5.0-py36hfa6e2cd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jupyter_client-5.2.3-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libnetcdf-4.6.1-h62daf8c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/nbformat-4.4.0-py36h3a5bc1b_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pip-10.0.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/prompt_toolkit-1.0.15-py36h60b8f86_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyopenssl-18.0.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/terminado-0.8.1-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipython-6.5.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/nbconvert-5.3.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/free/win-64/service_identity-17.0.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipykernel-4.8.2-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/twisted-18.4.0-py36hfa6e2cd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jupyter_console-5.2.0-py36h6d89b47_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/prometheus_client-0.3.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/qtconsole-4.3.1-py36h99a29a9_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/notebook-5.6.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/widgetsnbextension-3.3.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipywidgets-7.3.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jupyter-1.0.0-py36_4.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/cftime-1.0.0b1-py36h452e1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/matplotlib-2.2.2-py36h153e9ff_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl_fft-1.0.4-py36h1e22a9b_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl_random-1.0.1-py36h77b88f5_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.14.5-py36h9fa60d3_4.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/netcdf4-1.4.0-py36hbfe741f_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/scipy-1.1.0-py36h672f292_0.tar.bz2
